site_name: Code Thesaurus Documentation
theme:
  name: yeti
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  nav_style: primary
nav:
  - Home: index.md
  - Architecture: project_architecture
